### ISSUE TITLE
ImportError: No module named zbar

### ISSUE THREAD

**Issue by ilker-bekmezci** [zplab/zbar-py#13]
I installed iconv and then zbar-py (pip install zbar-py). 
And then I write import zbar into y code.
However, python cannot recognize the library.

The error is simple: 
Traceback (most recent call last):
  File "C:\Python27\GDrive\LAB\QRCODE_Read.py", line 16, in <module>
    import zbar
ImportError: No module named zbar

What can be the source of the error?

**Comment by zpincus** [comment]
This is not giving me a lot to go on. Please provide more information. Did the `pip install` command complete successfully? Could you include the output of that command?

How did you invoke the above script (`QRCODE_Read.py`) that led to the error?

Is it possible that you have multiple versions of python installed and that you used `pip` to install `zbar` into a different python version than was used in the script?
